<?php

use Carbon\Carbon as Carbon;
use Database\DisableForeignKeys;
use Database\TruncateTable;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionsTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    use DisableForeignKeys,
        TruncateTable;

    public function run() {
        $this->disableForeignKeys();
        $this->truncate('questions');
        $questions = [
            // BDI
            [
                'id' => 1,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Sadness',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Pessimism',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Past Failure',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Loss of Pleasure',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Guilty Feelings',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Punishmnet Feelings',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Self-Dislike',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Self-Criticalness',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Suicidal Thoughts or Wishes',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Crying',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Agitation',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Loss of Intrest',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Indecisiveness',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Worthlessness',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Loss of Energy',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 16,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Change in Sleeping Pattern',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 17,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Irritability',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 18,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Change in Appetite',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 19,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Concentartion Difficulty',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 20,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Tiredness of Fatigue',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 21,
                'type_id' => 1,
                'behaviour_id' => 0,
                'question' => 'Loss of Intrest in Sex',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            //** CORE
            [
                'id' => 22,
                'type_id' => 2,
                'behaviour_id' => 15,
                'question' => 'I have felt terribly alone and isolated',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 23,
                'type_id' => 2,
                'behaviour_id' => 14,
                'question' => 'I have felt tense, anxious or nervous',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'type_id' => 2,
                'behaviour_id' => 15,
                'question' => 'I have felt I have someone to turn to for support when needed',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 25,
                'type_id' => 2,
                'behaviour_id' => 13 ,
                'question' => 'I have felt OK about myself',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 26,
                'type_id' => 2,
                'behaviour_id' =>14 ,
                'question' => 'I have felt totally lacking in energy and enthusiasm',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 27,
                'type_id' => 2,
                'behaviour_id' => 16 ,
                'question' => 'I have been physically violent to others',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 28,
                'type_id' => 2,
                'behaviour_id' => 15,
                'question' => 'I have felt able to cope when things go wrong',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 29,
                'type_id' => 2,
                'behaviour_id' => 14,
                'question' => 'I have been troubled by aches, pains or other physical problems',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 30,
                'type_id' => 2,
                'behaviour_id' => 16,
                'question' => 'I have thought of hurting myself',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 31,
                'type_id' => 2,
                'behaviour_id' => 15 ,
                'question' => 'Talking to people has felt too much for me',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 32,
                'type_id' => 2,
                'behaviour_id' => 14 ,
                'question' => 'Tension and anxiety have prevented me doing important things',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 33,
                'type_id' => 2,
                'behaviour_id' => 15 ,
                'question' => 'I have been happy with the things I have done',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 34,
                'type_id' => 2,
                'behaviour_id' => 14 ,
                'question' => 'I have been disturbed by unwanted thoughts and feelings',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'id' => 35,
                'type_id' => 2,
                'behaviour_id' => 13 ,
                'question' => 'I have felt like crying',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 36,
                'type_id' => 2,
                'behaviour_id' => 14 ,
                'question' => 'I have felt panic or terror',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'id' => 37,
                'type_id' => 2,
                'behaviour_id' => 16 ,
                'question' => 'I made plans to end my life',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 38,
                'type_id' => 2,
                'behaviour_id' => 13 ,
                'question' => 'I have felt overwhelmed by my problems',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 39,
                'type_id' => 2,
                'behaviour_id' => 14 ,
                'question' => 'I have had difficulty getting to sleep or staying asleep',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 40,
                'type_id' => 2,
                'behaviour_id' => 15 ,
                'question' => 'I have felt warmth or affection for someone',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 41,
                'type_id' => 2,
                'behaviour_id' => 14 ,
                'question' => 'My problems have been impossible to put to one side',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 42,
                'type_id' => 2,
                'behaviour_id' => 15 ,
                'question' => 'I have been able to do most things I needed to',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 43,
                'type_id' => 2,
                'behaviour_id' => 16 ,
                'question' => 'I have threatened or intimidated another person',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 44,
                'type_id' => 2,
                'behaviour_id' => 14 ,
                'question' => 'I have felt despairing or hopeless',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 45,
                'type_id' => 2,
                'behaviour_id' => 16 ,
                'question' => 'I have thought it would be better if I were dead',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 46,
                'type_id' => 2,
                'behaviour_id' => 15,
                'question' => 'I have felt criticised by other people',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'id' => 47,
                'type_id' => 2,
                'behaviour_id' => 15 ,
                'question' => 'I have thought I have no friends',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 48,
                'type_id' => 2,
                'behaviour_id' => 14 ,
                'question' => 'I have felt unhappy',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 49,
                'type_id' => 2,
                'behaviour_id' => 14 ,
                'question' => 'Unwanted images or memories have been distressing me',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'id' => 50,
                'type_id' => 2,
                'behaviour_id' => 15,
                'question' => 'I have been irritable when with other people',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 51,
                'type_id' => 2,
                'behaviour_id' => 14 ,
                'question' => 'I have thought I am to blame for my problems and difficulties',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 52,
                'type_id' => 2,
                'behaviour_id' => 13 ,
                'question' => 'I have felt optimistic about my future',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 53,
                'type_id' => 2,
                'behaviour_id' => 15 ,
                'question' => 'I have achieved the things I wanted to',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 54,
                'type_id' => 2,
                'behaviour_id' => 15 ,
                'question' => 'I have felt humiliated or shamed by other people',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 55,
                'type_id' => 2,
                'behaviour_id' => 16 ,
                'question' => 'I have hurt myself physically or taken dangerous risks with my health',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // SDQ
            [
                'id' => 56,
                'type_id' => 3,
                'behaviour_id' => 5,
                'question' => 'I try to be nice to other people, I care about their feelings',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 57,
                'type_id' => 3,
                'behaviour_id' => 3,
                'question' => 'I am restless, I cannot stay still for long',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 58,
                'type_id' => 3,
                'behaviour_id' => 1,
                'question' => 'I ususally do as I am told',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 59,
                'type_id' => 3,
                'behaviour_id' => 5,
                'question' => 'I get lot of headaches,stomach-aches,or sickness',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 60,
                'type_id' => 3,
                'behaviour_id' => 2,
                'question' => 'I ususally share with others,for example CDs,games,food',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 61,
                'type_id' => 3,
                'behaviour_id' => 4,
                'question' => 'I get very angry and often lose my temper',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 62,
                'type_id' => 3,
                'behaviour_id' => 4,
                'question' => 'I would rather be alone than with people of my age',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 63,
                'type_id' => 3,
                'behaviour_id' => 2,
                'question' => 'I ususally do as i am told',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 64,
                'type_id' => 3,
                'behaviour_id' => 1,
                'question' => 'I worry a lot',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 65,
                'type_id' => 3,
                'behaviour_id' => 5,
                'question' => 'I am helpful if someone is hurt, apset or feeling ill',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 66,
                'type_id' => 3,
                'behaviour_id' => 3,
                'question' => 'I am constantly fidgeting or squirming',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 67,
                'type_id' => 3,
                'behaviour_id' => 4,
                'question' => 'I have one good friend or more',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 68,
                'type_id' => 3,
                'behaviour_id' => 2,
                'question' => 'I fight a lot. I can make other people do what I want',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 69,
                'type_id' => 3,
                'behaviour_id' => 1,
                'question' => 'I am often unhappy,depressed or tearful',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 70,
                'type_id' => 3,
                'behaviour_id' => 4,
                'question' => 'Other people my age generally like me ',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 71,
                'type_id' => 3,
                'behaviour_id' => 3,
                'question' => 'I am esaily distracted, I find difficult to concentrate ',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 72,
                'type_id' => 3,
                'behaviour_id' => 1,
                'question' => 'I am nervous in new situations. I easily lose confidence ',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 73,
                'type_id' => 3,
                'behaviour_id' => 5,
                'question' => 'I am kind to younger children ',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 74,
                'type_id' => 3,
                'behaviour_id' => 2,
                'question' => 'I am often accused of lying and cheating  ',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 75,
                'type_id' => 3,
                'behaviour_id' => 4,
                'question' => 'Other children or younger people pick on me or bully me ',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 76,
                'type_id' => 3,
                'behaviour_id' => 5,
                'question' => 'I often volunteer to help othera (parents,teachers,children) ',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 77,
                'type_id' => 3,
                'behaviour_id' => 3,
                'question' => 'I think before I do things ',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 78,
                'type_id' => 3,
                'behaviour_id' => 2,
                'question' => 'I take things that are not mine frome home, school or elsewhere ',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 79,
                'type_id' => 3,
                'behaviour_id' => 4,
                'question' => 'I get along better with adults than with people of my own age ',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 80,
                'type_id' => 3,
                'behaviour_id' => 1,
                'question' => 'I have many fears , I am easily scared ',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 81,
                'type_id' => 3,
                'behaviour_id' => 3,
                'question' => "I finish the work I'm doing. My attension is good",
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],



            // SCARED
            [
                'id' => 82,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'When I feel frightened, it is hard to breathe',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 83,
                'type_id' => 4,
                'behaviour_id' => 11,
                'question' => 'I get headaches when I am at school',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 84,
                'type_id' => 4,
                'behaviour_id' => 10,
                'question' => 'I don’t like to be with people I don’t know well',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 85,
                'type_id' => 4,
                'behaviour_id' => 9,
                'question' => 'I get scared if I sleep away from home',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 86,
                'type_id' => 4,
                'behaviour_id' => 8,
                'question' => 'I worry about other people liking me',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 87,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'When I get frightened, I feel like passing out',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 88,
                'type_id' => 4,
                'behaviour_id' => 8,
                'question' => 'I am nervous',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 89,
                'type_id' => 4,
                'behaviour_id' => 9,
                'question' => 'I follow my mother or father wherever they go',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 90,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'People tell me that I look nervous',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 91,
                'type_id' => 4,
                'behaviour_id' => 10,
                'question' => 'I feel nervous with people I don’t know well',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 92,
                'type_id' => 4,
                'behaviour_id' => 11,
                'question' => 'I get stomachaches at school',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 93,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'When I get frightened, I feel like I am going crazy',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 94,
                'type_id' => 4,
                'behaviour_id' => 9,
                'question' => 'I worry about sleeping alone',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 95,
                'type_id' => 4,
                'behaviour_id' => 8,
                'question' => 'I worry about being as good as other kids',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 96,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'When I get frightened, I feel like things are not real',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 97,
                'type_id' => 4,
                'behaviour_id' => 9,
                'question' => 'I have nightmares about something bad happening to my parents',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 98,
                'type_id' => 4,
                'behaviour_id' => 11,
                'question' => 'I worry about going to school',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 99,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'When I get frightened, my heart beats fast',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 100,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'I get shaky',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 101,
                'type_id' => 4,
                'behaviour_id' => 9,
                'question' => 'I have nightmares about something bad happening to me',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 102,
                'type_id' => 4,
                'behaviour_id' => 8,
                'question' => 'I worry about things working out for me',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 103,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'When I get frightened, I sweat a lot',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 104,
                'type_id' => 4,
                'behaviour_id' => 8,
                'question' => 'I am a worrier',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 105,
                'type_id' => 4,
                'behaviour_id' =>7 ,
                'question' => 'I get really frightened for no reason at all',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 106,
                'type_id' => 4,
                'behaviour_id' => 9,
                'question' => 'I am afraid to be alone in the house',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 107,
                'type_id' => 4,
                'behaviour_id' => 10,
                'question' => 'It is hard for me to talk with people I don’t know well',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 108,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'When I get frightened, I feel like I am choking',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 109,
                'type_id' => 4,
                'behaviour_id' => 8,
                'question' => 'People tell me that I worry too much',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 110,
                'type_id' => 4,
                'behaviour_id' => 9,
                'question' => 'I don’t like to be away from my family',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 111,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'I am afraid of having anxiety (or panic) attacks',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 112,
                'type_id' => 4,
                'behaviour_id' => 9,
                'question' => 'I worry that something bad might happen to my parents',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 113,
                'type_id' => 4,
                'behaviour_id' => 10,
                'question' => 'I feel shy with people I don’t know well',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 114,
                'type_id' => 4,
                'behaviour_id' => 8,
                'question' => 'I worry about what is going to happen in the future',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 115,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'When I get frightened, I feel like throwing up',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 116,
                'type_id' => 4,
                'behaviour_id' => 8,
                'question' => 'I worry about how well I do things',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 117,
                'type_id' => 4,
                'behaviour_id' => 11,
                'question' => 'I am scared to go to school',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 118,
                'type_id' => 4,
                'behaviour_id' => 8,
                'question' => 'I worry about things that have already happened',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'id' => 119,
                'type_id' => 4,
                'behaviour_id' => 7,
                'question' => 'When I get frightened, I feel dizzy',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 120,
                'type_id' => 4,
                'behaviour_id' => 10,
                'question' => 'I feel nervous when I am with other children or adults and I have to do
                    something while they watch me (for example: read aloud, speak, play a
                    game, play a sport)',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
             [
                'id' => 121,
                'type_id' => 4,
                'behaviour_id' => 10,
                'question' => 'I feel nervous when I am going to parties, dances, or any place where there
                    will be people that I don’t know well',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 122,
                'type_id' => 4,
                'behaviour_id' => 10,
                'question' => 'I am shy',
                'status' => 1,
                'created_by' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ];
        DB::table('questions')->insert($questions);
        $this->enableForeignKeys();
    }

}
